use axum::{
    Router, middleware,
    routing::{delete, get, post, put},
};

use crate::{
    infrastructure::web::middleware::{admin_middleware, auth_middleware},
    state::AppState,
};

use super::{construction, enterprise, log, role, stats, upload, user};

pub fn admin_routes() -> Router<AppState> {
    Router::new()
        .route("/log/level", post(log::handler::set_log_level))
        .route("/projects", get(construction::handler::list_projects))
        .route("/projects", post(construction::handler::create_project))
        .route(
            "/projects/options",
            get(construction::handler::list_project_options),
        )
        .route(
            "/projects/{id}",
            get(construction::handler::get_project)
                .put(construction::handler::update_project)
                .patch(construction::handler::update_project)
                .delete(construction::handler::delete_project),
        )
        .route(
            "/projects/{project_id}/units",
            get(construction::handler::list_units).post(construction::handler::create_unit),
        )
        .route(
            "/projects/{project_id}/units/{unit_id}",
            get(construction::handler::get_unit)
                .put(construction::handler::update_unit)
                .patch(construction::handler::update_unit)
                .delete(construction::handler::delete_unit),
        )
        .route(
            "/projects/{project_id}/teams",
            get(construction::handler::list_teams).post(construction::handler::create_team),
        )
        .route(
            "/projects/{project_id}/teams/{team_id}",
            get(construction::handler::get_team)
                .put(construction::handler::update_team)
                .patch(construction::handler::update_team)
                .delete(construction::handler::delete_team),
        )
        .route(
            "/projects/{project_id}/workers",
            get(construction::handler::list_workers).post(construction::handler::create_worker),
        )
        .route(
            "/projects/{project_id}/workers/{worker_id}",
            get(construction::handler::get_worker)
                .put(construction::handler::update_worker)
                .patch(construction::handler::update_worker)
                .delete(construction::handler::delete_worker),
        )
        .route(
            "/projects/{project_id}/workers/{worker_id}/contract-download",
            get(construction::handler::download_worker_contract),
        )
        .route(
            "/projects/{project_id}/contract-template",
            get(construction::handler::get_project_contract_template_config)
                .put(construction::handler::upsert_project_contract_template_config),
        )
        .route(
            "/projects/{project_id}/attendance-records",
            get(construction::handler::list_attendance)
                .post(construction::handler::create_attendance),
        )
        .route(
            "/projects/{project_id}/attendance-records/{attendance_id}",
            get(construction::handler::get_attendance)
                .put(construction::handler::update_attendance)
                .patch(construction::handler::update_attendance)
                .delete(construction::handler::delete_attendance),
        )
        .route(
            "/projects/{project_id}/attendance-devices",
            get(construction::handler::list_attendance_devices)
                .post(construction::handler::create_attendance_device),
        )
        .route(
            "/projects/{project_id}/attendance-devices/{device_id}",
            get(construction::handler::get_attendance_device)
                .put(construction::handler::update_attendance_device)
                .patch(construction::handler::update_attendance_device)
                .delete(construction::handler::delete_attendance_device),
        )
        .route(
            "/attendance-device-issue-reports",
            get(construction::handler::list_attendance_device_issue_reports)
                .post(construction::handler::create_attendance_device_issue_report),
        )
        .route(
            "/attendance-device-issue-reports/{report_id}",
            get(construction::handler::get_attendance_device_issue_report)
                .put(construction::handler::update_attendance_device_issue_report)
                .patch(construction::handler::update_attendance_device_issue_report)
                .delete(construction::handler::delete_attendance_device_issue_report),
        )
        .route(
            "/projects/{project_id}/wage-batches",
            get(construction::handler::list_wage_batches)
                .post(construction::handler::create_wage_batch),
        )
        .route(
            "/projects/{project_id}/wage-batches/import",
            post(construction::handler::import_wage_batch),
        )
        .route(
            "/projects/{project_id}/wage-batches/export",
            get(construction::handler::export_wage_batches),
        )
        .route(
            "/projects/{project_id}/wage-batches/{batch_id}",
            put(construction::handler::update_wage_batch)
                .patch(construction::handler::update_wage_batch)
                .delete(construction::handler::delete_wage_batch),
        )
        .route(
            "/contract-templates",
            get(construction::handler::list_contract_templates)
                .post(construction::handler::create_contract_template),
        )
        .route(
            "/contract-templates/{template_id}",
            get(construction::handler::get_contract_template)
                .put(construction::handler::update_contract_template)
                .patch(construction::handler::update_contract_template)
                .delete(construction::handler::delete_contract_template),
        )
        .route(
            "/work-hour-configs",
            get(construction::handler::list_work_hour_configs)
                .post(construction::handler::create_work_hour_config),
        )
        .route(
            "/work-hour-configs/{config_id}",
            get(construction::handler::get_work_hour_config)
                .put(construction::handler::update_work_hour_config)
                .patch(construction::handler::update_work_hour_config)
                .delete(construction::handler::delete_work_hour_config),
        )
        .route(
            "/platform-configs",
            get(construction::handler::list_platform_configs)
                .post(construction::handler::create_platform_config),
        )
        .route(
            "/platform-configs/{config_id}",
            get(construction::handler::get_platform_config)
                .put(construction::handler::update_platform_config)
                .patch(construction::handler::update_platform_config)
                .delete(construction::handler::delete_platform_config),
        )
        .route(
            "/platform-logs",
            get(construction::handler::list_platform_logs)
                .post(construction::handler::create_platform_log),
        )
        .route(
            "/platform-logs/{log_id}",
            get(construction::handler::get_platform_log)
                .put(construction::handler::update_platform_log)
                .patch(construction::handler::update_platform_log)
                .delete(construction::handler::delete_platform_log),
        )
        .route(
            "/construction-overview",
            get(construction::handler::get_construction_overview),
        )
        .route(
            "/enterprise-customers",
            get(enterprise::handler::list_enterprise_customers)
                .post(enterprise::handler::create_enterprise_customer),
        )
        .route(
            "/enterprise-customers/export",
            get(enterprise::handler::export_enterprise_customers),
        )
        .route(
            "/enterprise-customers/{customer_id}",
            get(enterprise::handler::get_enterprise_customer)
                .put(enterprise::handler::update_enterprise_customer)
                .patch(enterprise::handler::update_enterprise_customer)
                .delete(enterprise::handler::delete_enterprise_customer),
        )
        .route(
            "/enterprise-customers/{customer_id}/summary",
            get(enterprise::handler::get_enterprise_customer_summary),
        )
        .route(
            "/enterprise-own-entities",
            get(enterprise::handler::list_enterprise_own_entities)
                .post(enterprise::handler::create_enterprise_own_entity),
        )
        .route(
            "/enterprise-own-entities/export",
            get(enterprise::handler::export_enterprise_own_entities),
        )
        .route(
            "/enterprise-own-entities/{entity_id}",
            get(enterprise::handler::get_enterprise_own_entity)
                .put(enterprise::handler::update_enterprise_own_entity)
                .patch(enterprise::handler::update_enterprise_own_entity)
                .delete(enterprise::handler::delete_enterprise_own_entity),
        )
        .route(
            "/enterprise-projects",
            get(enterprise::handler::list_enterprise_projects)
                .post(enterprise::handler::create_enterprise_project),
        )
        .route(
            "/enterprise-projects/export",
            get(enterprise::handler::export_enterprise_projects),
        )
        .route(
            "/enterprise-projects/{project_id}",
            get(enterprise::handler::get_enterprise_project)
                .put(enterprise::handler::update_enterprise_project)
                .patch(enterprise::handler::update_enterprise_project)
                .delete(enterprise::handler::delete_enterprise_project),
        )
        .route(
            "/enterprise-projects/{project_id}/summary",
            get(enterprise::handler::get_enterprise_project_summary),
        )
        .route(
            "/enterprise-projects/{project_id}/issued-invoices",
            get(enterprise::handler::list_issued_invoices)
                .post(enterprise::handler::create_issued_invoice),
        )
        .route(
            "/enterprise-projects/{project_id}/issued-invoices/export",
            get(enterprise::handler::export_issued_invoices),
        )
        .route(
            "/enterprise-projects/{project_id}/issued-invoices/{record_id}",
            put(enterprise::handler::update_issued_invoice)
                .patch(enterprise::handler::update_issued_invoice)
                .delete(enterprise::handler::delete_issued_invoice),
        )
        .route(
            "/enterprise-projects/{project_id}/received-invoices",
            get(enterprise::handler::list_received_invoices)
                .post(enterprise::handler::create_received_invoice),
        )
        .route(
            "/enterprise-projects/{project_id}/received-invoices/export",
            get(enterprise::handler::export_received_invoices),
        )
        .route(
            "/enterprise-projects/{project_id}/received-invoices/{record_id}",
            put(enterprise::handler::update_received_invoice)
                .patch(enterprise::handler::update_received_invoice)
                .delete(enterprise::handler::delete_received_invoice),
        )
        .route(
            "/enterprise-projects/{project_id}/collections",
            get(enterprise::handler::list_collections).post(enterprise::handler::create_collection),
        )
        .route(
            "/enterprise-projects/{project_id}/collections/export",
            get(enterprise::handler::export_collections),
        )
        .route(
            "/enterprise-projects/{project_id}/collections/{record_id}",
            put(enterprise::handler::update_collection)
                .patch(enterprise::handler::update_collection)
                .delete(enterprise::handler::delete_collection),
        )
        .route(
            "/enterprise-projects/{project_id}/payments",
            get(enterprise::handler::list_payments).post(enterprise::handler::create_payment),
        )
        .route(
            "/enterprise-projects/{project_id}/payments/export",
            get(enterprise::handler::export_payments),
        )
        .route(
            "/enterprise-projects/{project_id}/payments/{record_id}",
            put(enterprise::handler::update_payment)
                .patch(enterprise::handler::update_payment)
                .delete(enterprise::handler::delete_payment),
        )
        .route("/roles", get(role::handler::list_roles))
        .route("/roles", post(role::handler::create_role))
        .route("/roles/{id}", delete(role::handler::delete_role))
        .route("/roles/{id}/menus", put(role::handler::update_role_menus))
        .route("/uploads", get(upload::handler::list_uploads))
        .route(
            "/users",
            get(user::handler::list_users).post(user::handler::create_user),
        )
        .route("/users/{id}/role", post(user::handler::update_user_role))
        .route(
            "/users/{id}/projects",
            put(user::handler::update_user_projects),
        )
        .route("/stats", get(stats::handler::get_dashboard_stats))
        .route_layer(middleware::from_fn(admin_middleware))
        .route_layer(middleware::from_fn(auth_middleware))
}
