/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppRegisterRouteImport } from './routes/app/register'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppSettingsSessionsRouteImport } from './routes/app/settings/sessions'
import { Route as AppSettingsSecurityRouteImport } from './routes/app/settings/security'
import { Route as AppSettingsProfileRouteImport } from './routes/app/settings/profile'
import { Route as AppAdminWorkHourConfigsRouteImport } from './routes/app/admin/work-hour-configs'
import { Route as AppAdminVideoMonitoringRouteImport } from './routes/app/admin/video-monitoring'
import { Route as AppAdminUsersRouteImport } from './routes/app/admin/users'
import { Route as AppAdminUploadsRouteImport } from './routes/app/admin/uploads'
import { Route as AppAdminSafetyManagementRouteImport } from './routes/app/admin/safety-management'
import { Route as AppAdminRolesRouteImport } from './routes/app/admin/roles'
import { Route as AppAdminRegistrationLeadsRouteImport } from './routes/app/admin/registration-leads'
import { Route as AppAdminQualitySafetyRouteImport } from './routes/app/admin/quality-safety'
import { Route as AppAdminProjectsRouteImport } from './routes/app/admin/projects'
import { Route as AppAdminPlatformIntegrationsRouteImport } from './routes/app/admin/platform-integrations'
import { Route as AppAdminPersonnelWorkersRouteImport } from './routes/app/admin/personnel-workers'
import { Route as AppAdminPersonnelRegistrationsRouteImport } from './routes/app/admin/personnel-registrations'
import { Route as AppAdminPersonnelQualificationsRouteImport } from './routes/app/admin/personnel-qualifications'
import { Route as AppAdminPersonnelContractsRouteImport } from './routes/app/admin/personnel-contracts'
import { Route as AppAdminPersonnelBadRecordsRouteImport } from './routes/app/admin/personnel-bad-records'
import { Route as AppAdminPersonnelApproversRouteImport } from './routes/app/admin/personnel-approvers'
import { Route as AppAdminPartyBuildingRouteImport } from './routes/app/admin/party-building'
import { Route as AppAdminMaterialManagementRouteImport } from './routes/app/admin/material-management'
import { Route as AppAdminEnvironmentMonitoringRouteImport } from './routes/app/admin/environment-monitoring'
import { Route as AppAdminEnterpriseReceivedInvoicesRouteImport } from './routes/app/admin/enterprise-received-invoices'
import { Route as AppAdminEnterpriseProjectsRouteImport } from './routes/app/admin/enterprise-projects'
import { Route as AppAdminEnterprisePaymentsRouteImport } from './routes/app/admin/enterprise-payments'
import { Route as AppAdminEnterpriseOwnEntitiesRouteImport } from './routes/app/admin/enterprise-own-entities'
import { Route as AppAdminEnterpriseIssuedInvoicesRouteImport } from './routes/app/admin/enterprise-issued-invoices'
import { Route as AppAdminEnterpriseCustomersRouteImport } from './routes/app/admin/enterprise-customers'
import { Route as AppAdminEnterpriseCollectionsRouteImport } from './routes/app/admin/enterprise-collections'
import { Route as AppAdminEmergencyManagementRouteImport } from './routes/app/admin/emergency-management'
import { Route as AppAdminContractTemplatesRouteImport } from './routes/app/admin/contract-templates'
import { Route as AppAdminConstructionSiteRouteImport } from './routes/app/admin/construction-site'
import { Route as AppAdminAttendanceDevicesRouteImport } from './routes/app/admin/attendance-devices'
import { Route as AppAdminAttendanceDeviceIssueReportsRouteImport } from './routes/app/admin/attendance-device-issue-reports'
import { Route as AppAdminApiKeysRouteImport } from './routes/app/admin/api-keys'
import { Route as AppAdminProjectsProjectIdRouteImport } from './routes/app/admin/projects.$projectId'
import { Route as AppAdminEnterpriseProjectsProjectIdRouteImport } from './routes/app/admin/enterprise-projects.$projectId'
import { Route as AppAdminEnterpriseCustomersCustomerIdRouteImport } from './routes/app/admin/enterprise-customers.$customerId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppSettingsSessionsRoute = AppSettingsSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppAdminWorkHourConfigsRoute = AppAdminWorkHourConfigsRouteImport.update({
  id: '/work-hour-configs',
  path: '/work-hour-configs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminVideoMonitoringRoute = AppAdminVideoMonitoringRouteImport.update({
  id: '/video-monitoring',
  path: '/video-monitoring',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUploadsRoute = AppAdminUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSafetyManagementRoute =
  AppAdminSafetyManagementRouteImport.update({
    id: '/safety-management',
    path: '/safety-management',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRegistrationLeadsRoute =
  AppAdminRegistrationLeadsRouteImport.update({
    id: '/registration-leads',
    path: '/registration-leads',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminQualitySafetyRoute = AppAdminQualitySafetyRouteImport.update({
  id: '/quality-safety',
  path: '/quality-safety',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminProjectsRoute = AppAdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPlatformIntegrationsRoute =
  AppAdminPlatformIntegrationsRouteImport.update({
    id: '/platform-integrations',
    path: '/platform-integrations',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminPersonnelWorkersRoute =
  AppAdminPersonnelWorkersRouteImport.update({
    id: '/personnel-workers',
    path: '/personnel-workers',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminPersonnelRegistrationsRoute =
  AppAdminPersonnelRegistrationsRouteImport.update({
    id: '/personnel-registrations',
    path: '/personnel-registrations',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminPersonnelQualificationsRoute =
  AppAdminPersonnelQualificationsRouteImport.update({
    id: '/personnel-qualifications',
    path: '/personnel-qualifications',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminPersonnelContractsRoute =
  AppAdminPersonnelContractsRouteImport.update({
    id: '/personnel-contracts',
    path: '/personnel-contracts',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminPersonnelBadRecordsRoute =
  AppAdminPersonnelBadRecordsRouteImport.update({
    id: '/personnel-bad-records',
    path: '/personnel-bad-records',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminPersonnelApproversRoute =
  AppAdminPersonnelApproversRouteImport.update({
    id: '/personnel-approvers',
    path: '/personnel-approvers',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminPartyBuildingRoute = AppAdminPartyBuildingRouteImport.update({
  id: '/party-building',
  path: '/party-building',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMaterialManagementRoute =
  AppAdminMaterialManagementRouteImport.update({
    id: '/material-management',
    path: '/material-management',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminEnvironmentMonitoringRoute =
  AppAdminEnvironmentMonitoringRouteImport.update({
    id: '/environment-monitoring',
    path: '/environment-monitoring',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminEnterpriseReceivedInvoicesRoute =
  AppAdminEnterpriseReceivedInvoicesRouteImport.update({
    id: '/enterprise-received-invoices',
    path: '/enterprise-received-invoices',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminEnterpriseProjectsRoute =
  AppAdminEnterpriseProjectsRouteImport.update({
    id: '/enterprise-projects',
    path: '/enterprise-projects',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminEnterprisePaymentsRoute =
  AppAdminEnterprisePaymentsRouteImport.update({
    id: '/enterprise-payments',
    path: '/enterprise-payments',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminEnterpriseOwnEntitiesRoute =
  AppAdminEnterpriseOwnEntitiesRouteImport.update({
    id: '/enterprise-own-entities',
    path: '/enterprise-own-entities',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminEnterpriseIssuedInvoicesRoute =
  AppAdminEnterpriseIssuedInvoicesRouteImport.update({
    id: '/enterprise-issued-invoices',
    path: '/enterprise-issued-invoices',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminEnterpriseCustomersRoute =
  AppAdminEnterpriseCustomersRouteImport.update({
    id: '/enterprise-customers',
    path: '/enterprise-customers',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminEnterpriseCollectionsRoute =
  AppAdminEnterpriseCollectionsRouteImport.update({
    id: '/enterprise-collections',
    path: '/enterprise-collections',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminEmergencyManagementRoute =
  AppAdminEmergencyManagementRouteImport.update({
    id: '/emergency-management',
    path: '/emergency-management',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminContractTemplatesRoute =
  AppAdminContractTemplatesRouteImport.update({
    id: '/contract-templates',
    path: '/contract-templates',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminConstructionSiteRoute =
  AppAdminConstructionSiteRouteImport.update({
    id: '/construction-site',
    path: '/construction-site',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminAttendanceDevicesRoute =
  AppAdminAttendanceDevicesRouteImport.update({
    id: '/attendance-devices',
    path: '/attendance-devices',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminAttendanceDeviceIssueReportsRoute =
  AppAdminAttendanceDeviceIssueReportsRouteImport.update({
    id: '/attendance-device-issue-reports',
    path: '/attendance-device-issue-reports',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminApiKeysRoute = AppAdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminProjectsProjectIdRoute =
  AppAdminProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AppAdminProjectsRoute,
  } as any)
const AppAdminEnterpriseProjectsProjectIdRoute =
  AppAdminEnterpriseProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AppAdminEnterpriseProjectsRoute,
  } as any)
const AppAdminEnterpriseCustomersCustomerIdRoute =
  AppAdminEnterpriseCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AppAdminEnterpriseCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/app/register': typeof AppRegisterRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/api-keys': typeof AppAdminApiKeysRoute
  '/app/admin/attendance-device-issue-reports': typeof AppAdminAttendanceDeviceIssueReportsRoute
  '/app/admin/attendance-devices': typeof AppAdminAttendanceDevicesRoute
  '/app/admin/construction-site': typeof AppAdminConstructionSiteRoute
  '/app/admin/contract-templates': typeof AppAdminContractTemplatesRoute
  '/app/admin/emergency-management': typeof AppAdminEmergencyManagementRoute
  '/app/admin/enterprise-collections': typeof AppAdminEnterpriseCollectionsRoute
  '/app/admin/enterprise-customers': typeof AppAdminEnterpriseCustomersRouteWithChildren
  '/app/admin/enterprise-issued-invoices': typeof AppAdminEnterpriseIssuedInvoicesRoute
  '/app/admin/enterprise-own-entities': typeof AppAdminEnterpriseOwnEntitiesRoute
  '/app/admin/enterprise-payments': typeof AppAdminEnterprisePaymentsRoute
  '/app/admin/enterprise-projects': typeof AppAdminEnterpriseProjectsRouteWithChildren
  '/app/admin/enterprise-received-invoices': typeof AppAdminEnterpriseReceivedInvoicesRoute
  '/app/admin/environment-monitoring': typeof AppAdminEnvironmentMonitoringRoute
  '/app/admin/material-management': typeof AppAdminMaterialManagementRoute
  '/app/admin/party-building': typeof AppAdminPartyBuildingRoute
  '/app/admin/personnel-approvers': typeof AppAdminPersonnelApproversRoute
  '/app/admin/personnel-bad-records': typeof AppAdminPersonnelBadRecordsRoute
  '/app/admin/personnel-contracts': typeof AppAdminPersonnelContractsRoute
  '/app/admin/personnel-qualifications': typeof AppAdminPersonnelQualificationsRoute
  '/app/admin/personnel-registrations': typeof AppAdminPersonnelRegistrationsRoute
  '/app/admin/personnel-workers': typeof AppAdminPersonnelWorkersRoute
  '/app/admin/platform-integrations': typeof AppAdminPlatformIntegrationsRoute
  '/app/admin/projects': typeof AppAdminProjectsRouteWithChildren
  '/app/admin/quality-safety': typeof AppAdminQualitySafetyRoute
  '/app/admin/registration-leads': typeof AppAdminRegistrationLeadsRoute
  '/app/admin/roles': typeof AppAdminRolesRoute
  '/app/admin/safety-management': typeof AppAdminSafetyManagementRoute
  '/app/admin/uploads': typeof AppAdminUploadsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/video-monitoring': typeof AppAdminVideoMonitoringRoute
  '/app/admin/work-hour-configs': typeof AppAdminWorkHourConfigsRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/settings/sessions': typeof AppSettingsSessionsRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/admin/enterprise-customers/$customerId': typeof AppAdminEnterpriseCustomersCustomerIdRoute
  '/app/admin/enterprise-projects/$projectId': typeof AppAdminEnterpriseProjectsProjectIdRoute
  '/app/admin/projects/$projectId': typeof AppAdminProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/login': typeof AppLoginRoute
  '/app/register': typeof AppRegisterRoute
  '/app': typeof AppIndexRoute
  '/app/admin/api-keys': typeof AppAdminApiKeysRoute
  '/app/admin/attendance-device-issue-reports': typeof AppAdminAttendanceDeviceIssueReportsRoute
  '/app/admin/attendance-devices': typeof AppAdminAttendanceDevicesRoute
  '/app/admin/construction-site': typeof AppAdminConstructionSiteRoute
  '/app/admin/contract-templates': typeof AppAdminContractTemplatesRoute
  '/app/admin/emergency-management': typeof AppAdminEmergencyManagementRoute
  '/app/admin/enterprise-collections': typeof AppAdminEnterpriseCollectionsRoute
  '/app/admin/enterprise-customers': typeof AppAdminEnterpriseCustomersRouteWithChildren
  '/app/admin/enterprise-issued-invoices': typeof AppAdminEnterpriseIssuedInvoicesRoute
  '/app/admin/enterprise-own-entities': typeof AppAdminEnterpriseOwnEntitiesRoute
  '/app/admin/enterprise-payments': typeof AppAdminEnterprisePaymentsRoute
  '/app/admin/enterprise-projects': typeof AppAdminEnterpriseProjectsRouteWithChildren
  '/app/admin/enterprise-received-invoices': typeof AppAdminEnterpriseReceivedInvoicesRoute
  '/app/admin/environment-monitoring': typeof AppAdminEnvironmentMonitoringRoute
  '/app/admin/material-management': typeof AppAdminMaterialManagementRoute
  '/app/admin/party-building': typeof AppAdminPartyBuildingRoute
  '/app/admin/personnel-approvers': typeof AppAdminPersonnelApproversRoute
  '/app/admin/personnel-bad-records': typeof AppAdminPersonnelBadRecordsRoute
  '/app/admin/personnel-contracts': typeof AppAdminPersonnelContractsRoute
  '/app/admin/personnel-qualifications': typeof AppAdminPersonnelQualificationsRoute
  '/app/admin/personnel-registrations': typeof AppAdminPersonnelRegistrationsRoute
  '/app/admin/personnel-workers': typeof AppAdminPersonnelWorkersRoute
  '/app/admin/platform-integrations': typeof AppAdminPlatformIntegrationsRoute
  '/app/admin/projects': typeof AppAdminProjectsRouteWithChildren
  '/app/admin/quality-safety': typeof AppAdminQualitySafetyRoute
  '/app/admin/registration-leads': typeof AppAdminRegistrationLeadsRoute
  '/app/admin/roles': typeof AppAdminRolesRoute
  '/app/admin/safety-management': typeof AppAdminSafetyManagementRoute
  '/app/admin/uploads': typeof AppAdminUploadsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/video-monitoring': typeof AppAdminVideoMonitoringRoute
  '/app/admin/work-hour-configs': typeof AppAdminWorkHourConfigsRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/settings/sessions': typeof AppSettingsSessionsRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/admin/enterprise-customers/$customerId': typeof AppAdminEnterpriseCustomersCustomerIdRoute
  '/app/admin/enterprise-projects/$projectId': typeof AppAdminEnterpriseProjectsProjectIdRoute
  '/app/admin/projects/$projectId': typeof AppAdminProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/app/register': typeof AppRegisterRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/api-keys': typeof AppAdminApiKeysRoute
  '/app/admin/attendance-device-issue-reports': typeof AppAdminAttendanceDeviceIssueReportsRoute
  '/app/admin/attendance-devices': typeof AppAdminAttendanceDevicesRoute
  '/app/admin/construction-site': typeof AppAdminConstructionSiteRoute
  '/app/admin/contract-templates': typeof AppAdminContractTemplatesRoute
  '/app/admin/emergency-management': typeof AppAdminEmergencyManagementRoute
  '/app/admin/enterprise-collections': typeof AppAdminEnterpriseCollectionsRoute
  '/app/admin/enterprise-customers': typeof AppAdminEnterpriseCustomersRouteWithChildren
  '/app/admin/enterprise-issued-invoices': typeof AppAdminEnterpriseIssuedInvoicesRoute
  '/app/admin/enterprise-own-entities': typeof AppAdminEnterpriseOwnEntitiesRoute
  '/app/admin/enterprise-payments': typeof AppAdminEnterprisePaymentsRoute
  '/app/admin/enterprise-projects': typeof AppAdminEnterpriseProjectsRouteWithChildren
  '/app/admin/enterprise-received-invoices': typeof AppAdminEnterpriseReceivedInvoicesRoute
  '/app/admin/environment-monitoring': typeof AppAdminEnvironmentMonitoringRoute
  '/app/admin/material-management': typeof AppAdminMaterialManagementRoute
  '/app/admin/party-building': typeof AppAdminPartyBuildingRoute
  '/app/admin/personnel-approvers': typeof AppAdminPersonnelApproversRoute
  '/app/admin/personnel-bad-records': typeof AppAdminPersonnelBadRecordsRoute
  '/app/admin/personnel-contracts': typeof AppAdminPersonnelContractsRoute
  '/app/admin/personnel-qualifications': typeof AppAdminPersonnelQualificationsRoute
  '/app/admin/personnel-registrations': typeof AppAdminPersonnelRegistrationsRoute
  '/app/admin/personnel-workers': typeof AppAdminPersonnelWorkersRoute
  '/app/admin/platform-integrations': typeof AppAdminPlatformIntegrationsRoute
  '/app/admin/projects': typeof AppAdminProjectsRouteWithChildren
  '/app/admin/quality-safety': typeof AppAdminQualitySafetyRoute
  '/app/admin/registration-leads': typeof AppAdminRegistrationLeadsRoute
  '/app/admin/roles': typeof AppAdminRolesRoute
  '/app/admin/safety-management': typeof AppAdminSafetyManagementRoute
  '/app/admin/uploads': typeof AppAdminUploadsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/video-monitoring': typeof AppAdminVideoMonitoringRoute
  '/app/admin/work-hour-configs': typeof AppAdminWorkHourConfigsRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/settings/sessions': typeof AppSettingsSessionsRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/admin/enterprise-customers/$customerId': typeof AppAdminEnterpriseCustomersCustomerIdRoute
  '/app/admin/enterprise-projects/$projectId': typeof AppAdminEnterpriseProjectsProjectIdRoute
  '/app/admin/projects/$projectId': typeof AppAdminProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/login'
    | '/app/register'
    | '/app/settings'
    | '/app/'
    | '/app/admin/api-keys'
    | '/app/admin/attendance-device-issue-reports'
    | '/app/admin/attendance-devices'
    | '/app/admin/construction-site'
    | '/app/admin/contract-templates'
    | '/app/admin/emergency-management'
    | '/app/admin/enterprise-collections'
    | '/app/admin/enterprise-customers'
    | '/app/admin/enterprise-issued-invoices'
    | '/app/admin/enterprise-own-entities'
    | '/app/admin/enterprise-payments'
    | '/app/admin/enterprise-projects'
    | '/app/admin/enterprise-received-invoices'
    | '/app/admin/environment-monitoring'
    | '/app/admin/material-management'
    | '/app/admin/party-building'
    | '/app/admin/personnel-approvers'
    | '/app/admin/personnel-bad-records'
    | '/app/admin/personnel-contracts'
    | '/app/admin/personnel-qualifications'
    | '/app/admin/personnel-registrations'
    | '/app/admin/personnel-workers'
    | '/app/admin/platform-integrations'
    | '/app/admin/projects'
    | '/app/admin/quality-safety'
    | '/app/admin/registration-leads'
    | '/app/admin/roles'
    | '/app/admin/safety-management'
    | '/app/admin/uploads'
    | '/app/admin/users'
    | '/app/admin/video-monitoring'
    | '/app/admin/work-hour-configs'
    | '/app/settings/profile'
    | '/app/settings/security'
    | '/app/settings/sessions'
    | '/app/admin/'
    | '/app/settings/'
    | '/app/admin/enterprise-customers/$customerId'
    | '/app/admin/enterprise-projects/$projectId'
    | '/app/admin/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/login'
    | '/app/register'
    | '/app'
    | '/app/admin/api-keys'
    | '/app/admin/attendance-device-issue-reports'
    | '/app/admin/attendance-devices'
    | '/app/admin/construction-site'
    | '/app/admin/contract-templates'
    | '/app/admin/emergency-management'
    | '/app/admin/enterprise-collections'
    | '/app/admin/enterprise-customers'
    | '/app/admin/enterprise-issued-invoices'
    | '/app/admin/enterprise-own-entities'
    | '/app/admin/enterprise-payments'
    | '/app/admin/enterprise-projects'
    | '/app/admin/enterprise-received-invoices'
    | '/app/admin/environment-monitoring'
    | '/app/admin/material-management'
    | '/app/admin/party-building'
    | '/app/admin/personnel-approvers'
    | '/app/admin/personnel-bad-records'
    | '/app/admin/personnel-contracts'
    | '/app/admin/personnel-qualifications'
    | '/app/admin/personnel-registrations'
    | '/app/admin/personnel-workers'
    | '/app/admin/platform-integrations'
    | '/app/admin/projects'
    | '/app/admin/quality-safety'
    | '/app/admin/registration-leads'
    | '/app/admin/roles'
    | '/app/admin/safety-management'
    | '/app/admin/uploads'
    | '/app/admin/users'
    | '/app/admin/video-monitoring'
    | '/app/admin/work-hour-configs'
    | '/app/settings/profile'
    | '/app/settings/security'
    | '/app/settings/sessions'
    | '/app/admin'
    | '/app/settings'
    | '/app/admin/enterprise-customers/$customerId'
    | '/app/admin/enterprise-projects/$projectId'
    | '/app/admin/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/login'
    | '/app/register'
    | '/app/settings'
    | '/app/'
    | '/app/admin/api-keys'
    | '/app/admin/attendance-device-issue-reports'
    | '/app/admin/attendance-devices'
    | '/app/admin/construction-site'
    | '/app/admin/contract-templates'
    | '/app/admin/emergency-management'
    | '/app/admin/enterprise-collections'
    | '/app/admin/enterprise-customers'
    | '/app/admin/enterprise-issued-invoices'
    | '/app/admin/enterprise-own-entities'
    | '/app/admin/enterprise-payments'
    | '/app/admin/enterprise-projects'
    | '/app/admin/enterprise-received-invoices'
    | '/app/admin/environment-monitoring'
    | '/app/admin/material-management'
    | '/app/admin/party-building'
    | '/app/admin/personnel-approvers'
    | '/app/admin/personnel-bad-records'
    | '/app/admin/personnel-contracts'
    | '/app/admin/personnel-qualifications'
    | '/app/admin/personnel-registrations'
    | '/app/admin/personnel-workers'
    | '/app/admin/platform-integrations'
    | '/app/admin/projects'
    | '/app/admin/quality-safety'
    | '/app/admin/registration-leads'
    | '/app/admin/roles'
    | '/app/admin/safety-management'
    | '/app/admin/uploads'
    | '/app/admin/users'
    | '/app/admin/video-monitoring'
    | '/app/admin/work-hour-configs'
    | '/app/settings/profile'
    | '/app/settings/security'
    | '/app/settings/sessions'
    | '/app/admin/'
    | '/app/settings/'
    | '/app/admin/enterprise-customers/$customerId'
    | '/app/admin/enterprise-projects/$projectId'
    | '/app/admin/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/register': {
      id: '/app/register'
      path: '/register'
      fullPath: '/app/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/settings/sessions': {
      id: '/app/settings/sessions'
      path: '/sessions'
      fullPath: '/app/settings/sessions'
      preLoaderRoute: typeof AppSettingsSessionsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/security': {
      id: '/app/settings/security'
      path: '/security'
      fullPath: '/app/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/profile': {
      id: '/app/settings/profile'
      path: '/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/admin/work-hour-configs': {
      id: '/app/admin/work-hour-configs'
      path: '/work-hour-configs'
      fullPath: '/app/admin/work-hour-configs'
      preLoaderRoute: typeof AppAdminWorkHourConfigsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/video-monitoring': {
      id: '/app/admin/video-monitoring'
      path: '/video-monitoring'
      fullPath: '/app/admin/video-monitoring'
      preLoaderRoute: typeof AppAdminVideoMonitoringRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/uploads': {
      id: '/app/admin/uploads'
      path: '/uploads'
      fullPath: '/app/admin/uploads'
      preLoaderRoute: typeof AppAdminUploadsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/safety-management': {
      id: '/app/admin/safety-management'
      path: '/safety-management'
      fullPath: '/app/admin/safety-management'
      preLoaderRoute: typeof AppAdminSafetyManagementRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/roles': {
      id: '/app/admin/roles'
      path: '/roles'
      fullPath: '/app/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/registration-leads': {
      id: '/app/admin/registration-leads'
      path: '/registration-leads'
      fullPath: '/app/admin/registration-leads'
      preLoaderRoute: typeof AppAdminRegistrationLeadsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/quality-safety': {
      id: '/app/admin/quality-safety'
      path: '/quality-safety'
      fullPath: '/app/admin/quality-safety'
      preLoaderRoute: typeof AppAdminQualitySafetyRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/projects': {
      id: '/app/admin/projects'
      path: '/projects'
      fullPath: '/app/admin/projects'
      preLoaderRoute: typeof AppAdminProjectsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/platform-integrations': {
      id: '/app/admin/platform-integrations'
      path: '/platform-integrations'
      fullPath: '/app/admin/platform-integrations'
      preLoaderRoute: typeof AppAdminPlatformIntegrationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/personnel-workers': {
      id: '/app/admin/personnel-workers'
      path: '/personnel-workers'
      fullPath: '/app/admin/personnel-workers'
      preLoaderRoute: typeof AppAdminPersonnelWorkersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/personnel-registrations': {
      id: '/app/admin/personnel-registrations'
      path: '/personnel-registrations'
      fullPath: '/app/admin/personnel-registrations'
      preLoaderRoute: typeof AppAdminPersonnelRegistrationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/personnel-qualifications': {
      id: '/app/admin/personnel-qualifications'
      path: '/personnel-qualifications'
      fullPath: '/app/admin/personnel-qualifications'
      preLoaderRoute: typeof AppAdminPersonnelQualificationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/personnel-contracts': {
      id: '/app/admin/personnel-contracts'
      path: '/personnel-contracts'
      fullPath: '/app/admin/personnel-contracts'
      preLoaderRoute: typeof AppAdminPersonnelContractsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/personnel-bad-records': {
      id: '/app/admin/personnel-bad-records'
      path: '/personnel-bad-records'
      fullPath: '/app/admin/personnel-bad-records'
      preLoaderRoute: typeof AppAdminPersonnelBadRecordsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/personnel-approvers': {
      id: '/app/admin/personnel-approvers'
      path: '/personnel-approvers'
      fullPath: '/app/admin/personnel-approvers'
      preLoaderRoute: typeof AppAdminPersonnelApproversRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/party-building': {
      id: '/app/admin/party-building'
      path: '/party-building'
      fullPath: '/app/admin/party-building'
      preLoaderRoute: typeof AppAdminPartyBuildingRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/material-management': {
      id: '/app/admin/material-management'
      path: '/material-management'
      fullPath: '/app/admin/material-management'
      preLoaderRoute: typeof AppAdminMaterialManagementRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/environment-monitoring': {
      id: '/app/admin/environment-monitoring'
      path: '/environment-monitoring'
      fullPath: '/app/admin/environment-monitoring'
      preLoaderRoute: typeof AppAdminEnvironmentMonitoringRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/enterprise-received-invoices': {
      id: '/app/admin/enterprise-received-invoices'
      path: '/enterprise-received-invoices'
      fullPath: '/app/admin/enterprise-received-invoices'
      preLoaderRoute: typeof AppAdminEnterpriseReceivedInvoicesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/enterprise-projects': {
      id: '/app/admin/enterprise-projects'
      path: '/enterprise-projects'
      fullPath: '/app/admin/enterprise-projects'
      preLoaderRoute: typeof AppAdminEnterpriseProjectsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/enterprise-payments': {
      id: '/app/admin/enterprise-payments'
      path: '/enterprise-payments'
      fullPath: '/app/admin/enterprise-payments'
      preLoaderRoute: typeof AppAdminEnterprisePaymentsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/enterprise-own-entities': {
      id: '/app/admin/enterprise-own-entities'
      path: '/enterprise-own-entities'
      fullPath: '/app/admin/enterprise-own-entities'
      preLoaderRoute: typeof AppAdminEnterpriseOwnEntitiesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/enterprise-issued-invoices': {
      id: '/app/admin/enterprise-issued-invoices'
      path: '/enterprise-issued-invoices'
      fullPath: '/app/admin/enterprise-issued-invoices'
      preLoaderRoute: typeof AppAdminEnterpriseIssuedInvoicesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/enterprise-customers': {
      id: '/app/admin/enterprise-customers'
      path: '/enterprise-customers'
      fullPath: '/app/admin/enterprise-customers'
      preLoaderRoute: typeof AppAdminEnterpriseCustomersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/enterprise-collections': {
      id: '/app/admin/enterprise-collections'
      path: '/enterprise-collections'
      fullPath: '/app/admin/enterprise-collections'
      preLoaderRoute: typeof AppAdminEnterpriseCollectionsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/emergency-management': {
      id: '/app/admin/emergency-management'
      path: '/emergency-management'
      fullPath: '/app/admin/emergency-management'
      preLoaderRoute: typeof AppAdminEmergencyManagementRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/contract-templates': {
      id: '/app/admin/contract-templates'
      path: '/contract-templates'
      fullPath: '/app/admin/contract-templates'
      preLoaderRoute: typeof AppAdminContractTemplatesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/construction-site': {
      id: '/app/admin/construction-site'
      path: '/construction-site'
      fullPath: '/app/admin/construction-site'
      preLoaderRoute: typeof AppAdminConstructionSiteRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/attendance-devices': {
      id: '/app/admin/attendance-devices'
      path: '/attendance-devices'
      fullPath: '/app/admin/attendance-devices'
      preLoaderRoute: typeof AppAdminAttendanceDevicesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/attendance-device-issue-reports': {
      id: '/app/admin/attendance-device-issue-reports'
      path: '/attendance-device-issue-reports'
      fullPath: '/app/admin/attendance-device-issue-reports'
      preLoaderRoute: typeof AppAdminAttendanceDeviceIssueReportsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/api-keys': {
      id: '/app/admin/api-keys'
      path: '/api-keys'
      fullPath: '/app/admin/api-keys'
      preLoaderRoute: typeof AppAdminApiKeysRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/projects/$projectId': {
      id: '/app/admin/projects/$projectId'
      path: '/$projectId'
      fullPath: '/app/admin/projects/$projectId'
      preLoaderRoute: typeof AppAdminProjectsProjectIdRouteImport
      parentRoute: typeof AppAdminProjectsRoute
    }
    '/app/admin/enterprise-projects/$projectId': {
      id: '/app/admin/enterprise-projects/$projectId'
      path: '/$projectId'
      fullPath: '/app/admin/enterprise-projects/$projectId'
      preLoaderRoute: typeof AppAdminEnterpriseProjectsProjectIdRouteImport
      parentRoute: typeof AppAdminEnterpriseProjectsRoute
    }
    '/app/admin/enterprise-customers/$customerId': {
      id: '/app/admin/enterprise-customers/$customerId'
      path: '/$customerId'
      fullPath: '/app/admin/enterprise-customers/$customerId'
      preLoaderRoute: typeof AppAdminEnterpriseCustomersCustomerIdRouteImport
      parentRoute: typeof AppAdminEnterpriseCustomersRoute
    }
  }
}

interface AppAdminEnterpriseCustomersRouteChildren {
  AppAdminEnterpriseCustomersCustomerIdRoute: typeof AppAdminEnterpriseCustomersCustomerIdRoute
}

const AppAdminEnterpriseCustomersRouteChildren: AppAdminEnterpriseCustomersRouteChildren =
  {
    AppAdminEnterpriseCustomersCustomerIdRoute:
      AppAdminEnterpriseCustomersCustomerIdRoute,
  }

const AppAdminEnterpriseCustomersRouteWithChildren =
  AppAdminEnterpriseCustomersRoute._addFileChildren(
    AppAdminEnterpriseCustomersRouteChildren,
  )

interface AppAdminEnterpriseProjectsRouteChildren {
  AppAdminEnterpriseProjectsProjectIdRoute: typeof AppAdminEnterpriseProjectsProjectIdRoute
}

const AppAdminEnterpriseProjectsRouteChildren: AppAdminEnterpriseProjectsRouteChildren =
  {
    AppAdminEnterpriseProjectsProjectIdRoute:
      AppAdminEnterpriseProjectsProjectIdRoute,
  }

const AppAdminEnterpriseProjectsRouteWithChildren =
  AppAdminEnterpriseProjectsRoute._addFileChildren(
    AppAdminEnterpriseProjectsRouteChildren,
  )

interface AppAdminProjectsRouteChildren {
  AppAdminProjectsProjectIdRoute: typeof AppAdminProjectsProjectIdRoute
}

const AppAdminProjectsRouteChildren: AppAdminProjectsRouteChildren = {
  AppAdminProjectsProjectIdRoute: AppAdminProjectsProjectIdRoute,
}

const AppAdminProjectsRouteWithChildren =
  AppAdminProjectsRoute._addFileChildren(AppAdminProjectsRouteChildren)

interface AppAdminRouteChildren {
  AppAdminApiKeysRoute: typeof AppAdminApiKeysRoute
  AppAdminAttendanceDeviceIssueReportsRoute: typeof AppAdminAttendanceDeviceIssueReportsRoute
  AppAdminAttendanceDevicesRoute: typeof AppAdminAttendanceDevicesRoute
  AppAdminConstructionSiteRoute: typeof AppAdminConstructionSiteRoute
  AppAdminContractTemplatesRoute: typeof AppAdminContractTemplatesRoute
  AppAdminEmergencyManagementRoute: typeof AppAdminEmergencyManagementRoute
  AppAdminEnterpriseCollectionsRoute: typeof AppAdminEnterpriseCollectionsRoute
  AppAdminEnterpriseCustomersRoute: typeof AppAdminEnterpriseCustomersRouteWithChildren
  AppAdminEnterpriseIssuedInvoicesRoute: typeof AppAdminEnterpriseIssuedInvoicesRoute
  AppAdminEnterpriseOwnEntitiesRoute: typeof AppAdminEnterpriseOwnEntitiesRoute
  AppAdminEnterprisePaymentsRoute: typeof AppAdminEnterprisePaymentsRoute
  AppAdminEnterpriseProjectsRoute: typeof AppAdminEnterpriseProjectsRouteWithChildren
  AppAdminEnterpriseReceivedInvoicesRoute: typeof AppAdminEnterpriseReceivedInvoicesRoute
  AppAdminEnvironmentMonitoringRoute: typeof AppAdminEnvironmentMonitoringRoute
  AppAdminMaterialManagementRoute: typeof AppAdminMaterialManagementRoute
  AppAdminPartyBuildingRoute: typeof AppAdminPartyBuildingRoute
  AppAdminPersonnelApproversRoute: typeof AppAdminPersonnelApproversRoute
  AppAdminPersonnelBadRecordsRoute: typeof AppAdminPersonnelBadRecordsRoute
  AppAdminPersonnelContractsRoute: typeof AppAdminPersonnelContractsRoute
  AppAdminPersonnelQualificationsRoute: typeof AppAdminPersonnelQualificationsRoute
  AppAdminPersonnelRegistrationsRoute: typeof AppAdminPersonnelRegistrationsRoute
  AppAdminPersonnelWorkersRoute: typeof AppAdminPersonnelWorkersRoute
  AppAdminPlatformIntegrationsRoute: typeof AppAdminPlatformIntegrationsRoute
  AppAdminProjectsRoute: typeof AppAdminProjectsRouteWithChildren
  AppAdminQualitySafetyRoute: typeof AppAdminQualitySafetyRoute
  AppAdminRegistrationLeadsRoute: typeof AppAdminRegistrationLeadsRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppAdminSafetyManagementRoute: typeof AppAdminSafetyManagementRoute
  AppAdminUploadsRoute: typeof AppAdminUploadsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminVideoMonitoringRoute: typeof AppAdminVideoMonitoringRoute
  AppAdminWorkHourConfigsRoute: typeof AppAdminWorkHourConfigsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminApiKeysRoute: AppAdminApiKeysRoute,
  AppAdminAttendanceDeviceIssueReportsRoute:
    AppAdminAttendanceDeviceIssueReportsRoute,
  AppAdminAttendanceDevicesRoute: AppAdminAttendanceDevicesRoute,
  AppAdminConstructionSiteRoute: AppAdminConstructionSiteRoute,
  AppAdminContractTemplatesRoute: AppAdminContractTemplatesRoute,
  AppAdminEmergencyManagementRoute: AppAdminEmergencyManagementRoute,
  AppAdminEnterpriseCollectionsRoute: AppAdminEnterpriseCollectionsRoute,
  AppAdminEnterpriseCustomersRoute:
    AppAdminEnterpriseCustomersRouteWithChildren,
  AppAdminEnterpriseIssuedInvoicesRoute: AppAdminEnterpriseIssuedInvoicesRoute,
  AppAdminEnterpriseOwnEntitiesRoute: AppAdminEnterpriseOwnEntitiesRoute,
  AppAdminEnterprisePaymentsRoute: AppAdminEnterprisePaymentsRoute,
  AppAdminEnterpriseProjectsRoute: AppAdminEnterpriseProjectsRouteWithChildren,
  AppAdminEnterpriseReceivedInvoicesRoute:
    AppAdminEnterpriseReceivedInvoicesRoute,
  AppAdminEnvironmentMonitoringRoute: AppAdminEnvironmentMonitoringRoute,
  AppAdminMaterialManagementRoute: AppAdminMaterialManagementRoute,
  AppAdminPartyBuildingRoute: AppAdminPartyBuildingRoute,
  AppAdminPersonnelApproversRoute: AppAdminPersonnelApproversRoute,
  AppAdminPersonnelBadRecordsRoute: AppAdminPersonnelBadRecordsRoute,
  AppAdminPersonnelContractsRoute: AppAdminPersonnelContractsRoute,
  AppAdminPersonnelQualificationsRoute: AppAdminPersonnelQualificationsRoute,
  AppAdminPersonnelRegistrationsRoute: AppAdminPersonnelRegistrationsRoute,
  AppAdminPersonnelWorkersRoute: AppAdminPersonnelWorkersRoute,
  AppAdminPlatformIntegrationsRoute: AppAdminPlatformIntegrationsRoute,
  AppAdminProjectsRoute: AppAdminProjectsRouteWithChildren,
  AppAdminQualitySafetyRoute: AppAdminQualitySafetyRoute,
  AppAdminRegistrationLeadsRoute: AppAdminRegistrationLeadsRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppAdminSafetyManagementRoute: AppAdminSafetyManagementRoute,
  AppAdminUploadsRoute: AppAdminUploadsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminVideoMonitoringRoute: AppAdminVideoMonitoringRoute,
  AppAdminWorkHourConfigsRoute: AppAdminWorkHourConfigsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsSessionsRoute: typeof AppSettingsSessionsRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsSessionsRoute: AppSettingsSessionsRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
